name: Création de l'image

on: 
   push: 
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    #Recupertaion du code source
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and run zizmor audit
        run: |
          pip install zizmor
          zizmor .github/workflows/Build.yml
          
    #Connexion au registre
      - name: Connexion au registre de Github
        uses: docker/login-action@v3
        with:
          context:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    #Construction de l'image
      - name: Construction de l'image docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/donassongui/mon-site:latest
